name: creater_management
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  get: ^4.6.5
  api_cache_manager: ^1.0.2
  shared_preferences: ^2.0.15
  fluttertoast: ^8.1.2
  awesome_dialog: ^3.0.2
  firebase_core: ^2.4.0
  firebase_auth: ^4.2.1
  provider: ^6.0.5
  font_awesome_flutter: ^10.3.0
  custom_refresh_indicator: ^2.0.1
  page_transition: ^2.0.9
#  connectivity_plus: ^3.0.2
  flutter_offline: ^2.0.0
  sn_progress_dialog: ^1.0.9
  http: ^0.13.5
  flutter_screenutil: ^5.6.0
  image_picker: ^0.8.6
  loading_animations: ^2.2.0
  dio: ^4.0.6
  path_provider: ^2.0.11
  cached_network_image: ^3.2.3
  auto_size_text: ^3.0.0
  extended_nested_scroll_view: ^5.1.3
  firebase_messaging: ^14.2.0
  #  firebase_messaging: ^11.2.0
  flutter_local_notifications: ^13.0.0
  #  flutter_local_notifications: ^9.2.0
  cloud_firestore: ^4.2.0
  gsform: ^0.1.5
#  syncfusion_flutter_sliders: ^20.3.59
#  syncfusion_flutter_charts: ^20.3.59
  fl_chart: ^0.55.2
#  syncfusion_flutter_gauges: ^20.3.59
  skeleton_loader: ^2.0.0+4
  liquid_pull_to_refresh: ^3.0.1
#  flutter_app_version_checker: ^0.3.1
  container_tab_indicator: ^0.3.0
  google_fonts: ^3.0.1
  flutter_custom_clippers: ^2.0.0
  otp_text_field: ^1.1.3
  swipe_refresh: ^1.0.2
  flutter_insta: ^1.0.1
  youtube_data_api: ^1.0.4
  skeleton_animation: ^0.1.4
  flutter_linkify: ^5.0.2
  url_launcher: ^6.1.7
#  flutter_phone_direct_caller: ^2.1.1
  dropdown_textfield: ^1.0.7

#  otp_autofill: ^2.1.0
  sms_autofill: ^2.2.0
  timer_count_down: ^2.2.2
  share_plus: ^6.3.1

dev_dependencies:
  firebase_core_platform_interface: 4.5.2
  change_app_package_name: ^1.1.0
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/NOV-LOGO-red.png"
  adaptive_icon_foreground: "assets/images/NOV-LOGO-red.png"
  adaptive_icon_background: "#ed1e79"



flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
